# 실습 6
20206617 박주희

- 1장 프로그래밍 실습 문제 2

In [ ]:
import numpy as np
A = np.array([[1,2,3], # 3x3 행렬
              [4,5,6],
              [7,8,9]])

v = np.array([[1], # 3x1 행렬 벡터 v 생성
             [2],
             [3]])

print("A =",A)
print("v =",v)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
v = [[1]
 [2]
 [3]]


- 2장 프로그래밍 실습의 문제 1

In [ ]:
import numpy as np

a = np.zeros((2,3)) # 2x3 영행렬
print("a=",a)

b = np.ones((2,2)) # 모든 성분이 1인 2x2행렬
print("b=",b)

c = np.full((3,2),3) # 모든 성분이 3인 3x2행렬
print("c=",c)

d = np.eye(2) # 2x2 단위행렬
print("d=",d)

a= [[0. 0. 0.]
 [0. 0. 0.]]
b= [[1. 1.]
 [1. 1.]]
c= [[3 3]
 [3 3]
 [3 3]]
d= [[1. 0.]
 [0. 1.]]


- 3장 프로그래밍 실습의 문제 1과 2

In [ ]:
import numpy as np

print("벡터의 결합에 의한 행렬 생성")
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])

A = np.vstack([v1,v2,v3]) #v1,v2,v3를 각각 행으로 하는 행렬 A생성
print("A=",A)

B = np.column_stack([v1,v2,v3]) #v1,v2,v3를 각각 열으로 하는 행렬 A생성
print("B=",B)

C = np.array([[1,2],[3,4],[5,6]])
print("C=",C)

D = np.column_stack([C,v3]) #행렬 C에 v3를 열로 추가해 행렬 D생성
print("D=",D)

print("")
print("행렬의 성분 접근")
E = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("E[0,3]=",E[0,3]) #1행4열
print("E[1,2]=",E[1,2]) #2행3열

print("E[0:2,2]=",E[0:2,2]) #E의 1~2행의 3열의 부분행렬
print("E[0:2,2:4]=",E[0:2,2:4]) #E의 1~2행의 3~4열의 부분행렬
print("E[2,:]=",E[2,:]) # E의 3행의 부분행렬

print("")

print("성분의 변경")
print("E=",E)

print("E[0,0]=",E[0,0])
E[0,0]=-1 # E의 1행 1열 성분 -1로 변경
print(E)
print("E[0,0]=",E[0,0] )

벡터의 결합에 의한 행렬 생성
A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
B= [[1 4 7]
 [2 5 8]
 [3 6 9]]
C= [[1 2]
 [3 4]
 [5 6]]
D= [[1 2 7]
 [3 4 8]
 [5 6 9]]

행렬의 성분 접근
E[0,3]= 4
E[1,2]= 7
E[0:2,2]= [3 7]
E[0:2,2:4]= [[3 4]
 [7 8]]
E[2,:]= [ 9 10 11 12]

성분의 변경
E= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0]= 1
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0]= -1


In [ ]:
import numpy as np

def pprint(msg, A):
  print("---", msg , "---")
  (n,m) = A.shape
  for i in range(0,n):
    line = ""
    for j in range(0,m):
      line+= "{0:.2f}".format(A[i,j])+"\t"
    print(line)
  print("")

A= np.array([[1.,2.],[3.,4.]])
B = np.array([[2.,2.],[1.,3.]])
C = np.array([[4.,5.,6.,],[7.,8.,9.]])
v = np.array([[10.],[20.]])

pprint("A+B=",A+B)
pprint("A-B=",A-B)

pprint("3*A=",3*A)
pprint("2*v=",2*v) #행렬과 벡터의 곱 Av

pprint("matmul(A,B)",np.matmul(A,B))
pprint("matmul(A,C)",np.matmul(A,C))
pprint("A*v",A*v)

pprint("matrix_power(A,2)",np.linalg.matrix_power(A,2))
pprint("matrix_power(A,3)",np.linalg.matrix_power(A,3))

pprint("A*B=",A*B)
pprint("A/B=",A/B)
pprint("A**2= A**A",A**2)

pprint("A.T",A.T*v) # 행렬의 전치
pprint("v.T",v.T) #벡터의 전치

M = np.diag([1,2,3]) #대각행렬 생성
pprint("diag(1,2,3)=",M)

D11 = np.array([[1,2],[3,4]])
D12 = np.array([[5],[6]])
D21 = np.array([[7,7]])
D22 = np.array([[8]])
D = np.block([[D11,D12],[D21,D22]]) #블록행렬 D생성
pprint("block matrix",D)

--- A+B= ---
3.00	4.00	
4.00	7.00	

--- A-B= ---
-1.00	0.00	
2.00	1.00	

--- 3*A= ---
3.00	6.00	
9.00	12.00	

--- 2*v= ---
20.00	
40.00	

--- matmul(A,B) ---
4.00	8.00	
10.00	18.00	

--- matmul(A,C) ---
18.00	21.00	24.00	
40.00	47.00	54.00	

--- A*v ---
10.00	20.00	
60.00	80.00	

--- matrix_power(A,2) ---
7.00	10.00	
15.00	22.00	

--- matrix_power(A,3) ---
37.00	54.00	
81.00	118.00	

--- A*B= ---
2.00	4.00	
3.00	12.00	

--- A/B= ---
0.50	1.00	
3.00	1.33	

--- A**2= A**A ---
1.00	4.00	
9.00	16.00	

--- A.T ---
10.00	30.00	
40.00	80.00	

--- v.T ---
10.00	20.00	

--- diag(1,2,3)= ---
1.00	0.00	0.00	
0.00	2.00	0.00	
0.00	0.00	3.00	

--- block matrix ---
1.00	2.00	5.00	
3.00	4.00	6.00	
7.00	7.00	8.00	

