# inverse matrix 계산

In [ ]:
import numpy as np

def pprint(msg,A):
    print("---",msg, "---")
    (n,m)= A.shape
    for i in range(0,n):
        line = ""
        for j in range(0,m):
            line += "{0:.2f}".format(A[i,j])+ "\t"
        print(line)
    print("")

A = np.array([[1.,2.],[3.,4.]])
pprint("A",A)

Ainv1 = np.linalg.matrix_power(A,-1)
pprint("linalg.matrix_power(A,-1) => Ainv1", Ainv1)

Ainv2 = np.linalg.inv(A)
pprint(" np.linalg.inv((A) => Ainv2", Ainv2)

pprint("A*Ainv1",np.matmul(A,Ainv1))
pprint("A*Ainv2",np.matmul(A,Ainv2))

B = np.random.rand(3,3)
pprint("B=",B)
Binv = np.linalg.inv(B)
pprint("Binv = ",Binv)
pprint("B*Binv=",np.matmul(B, Binv))

C = np.array([[5,3,2,1],[6,2,4,5],[7,4,1,3],[4,3,5,2]])
D= np.array([[4],[2],[5],[1]])
x = np.matmul(np.linalg.inv(C),D)
pprint("x",x)
pprint("C*x",np.matmul(C,x))

--- A ---
1.00	2.00	
3.00	4.00	

--- linalg.matrix_power(A,-1) => Ainv1 ---
-2.00	1.00	
1.50	-0.50	

---  np.linalg.inv((A) => Ainv2 ---
-2.00	1.00	
1.50	-0.50	

--- A*Ainv1 ---
1.00	0.00	
0.00	1.00	

--- A*Ainv2 ---
1.00	0.00	
0.00	1.00	

--- B= ---
0.34	0.78	0.66	
0.54	0.99	0.66	
0.88	0.16	0.02	

--- Binv =  ---
0.79	-0.84	1.35	
-5.38	5.46	-1.32	
7.47	-6.03	0.87	

--- B*Binv= ---
1.00	-0.00	0.00	
-0.00	1.00	0.00	
0.00	-0.00	1.00	

--- x ---
1.31	
-0.38	
-0.31	
-0.77	

--- C*x ---
4.00	
2.00	
5.00	
1.00	



# Determinant(행렬식) 계산하기

In [ ]:
#5-2
import numpy as np

def determinant(M):
  if len(M) == 2:
    return M[0,0]*M[1,1]-M[0,1]*M[1,0]

a = np.array([[2,1],[4,5]])
b = np.array([[4,3],[1,7]])
print("a=",a)
print("det(a)=",determinant(a))
print("")
print("b=",b)
print("det(b)=",determinant(b))

a= [[2 1]
 [4 5]]
det(a)= 6

b= [[4 3]
 [1 7]]
det(b)= 25


In [ ]:
#5-3
import numpy as np

c = np.array([[5,2,3],[3,-1,1],[6,4,2]])
d = np.array([[3,2,3],[6,1,2],[1,2,5]])

detC = np.linalg.det(c)
detD = np.linalg.det(d)

print("c=",c)
print("det(c)=",round(detC))
print("")
print("d=",d)
print("det(d)=",round(detD))

c= [[ 5  2  3]
 [ 3 -1  1]
 [ 6  4  2]]
det(c)= 24

d= [[3 2 3]
 [6 1 2]
 [1 2 5]]
det(d)= -20


In [ ]:
#5-7(a)
import numpy as np

a = np.array([[1,5,-6],[-1,-4,4],[-2,-7,9]])
detA = np.linalg.det(a)

print("a=",a)
print("det(a)=",round(detA))

a= [[ 1  5 -6]
 [-1 -4  4]
 [-2 -7  9]]
det(a)= 3


In [ ]:
#5-8(a)
import numpy as np

a = np.array([[1,3,0,2],[-2,-5,7,4],[3,5,2,1],[1,-1,2,-3]])
detA = np.linalg.det(a)

print("a=",a)
print("det(a)=",round(detA))

a= [[ 1  3  0  2]
 [-2 -5  7  4]
 [ 3  5  2  1]
 [ 1 -1  2 -3]]
det(a)= 0


In [ ]:
#5-19(c)
import numpy as np

def determinant(M):
  if len(M) == 2:
    return M[0,0]*M[1,1]-M[0,1]*M[1,0]

c = np.array([[5,6,0,0],[3,7,0,0],[1,2,2,1],[3,1,3,7]])
a = np.array(([5,6],[3,7]))
b = np.array([[2,1],[3,7]])

print("c=",c)
print("det(a)=",determinant(a))
print("det(b)=",determinant(b))
print("a x b=",determinant(a)*determinant(b))

c= [[5 6 0 0]
 [3 7 0 0]
 [1 2 2 1]
 [3 1 3 7]]
det(a)= 17
det(b)= 11
a x b= 187


In [ ]:
#5-27(a)
import numpy as np

def cofactor(A,i,j):
  (n,m) = A.shape
  M = np.zeros((n-1,m-1))
  for a in range(0,n-1):
    k = a if (a<i) else a+1
    for b in range(0,m-1):
      l = b if (b<j) else b+1
      M[a,b] = A[k,l]

  return (-1)**(i+j)*np.linalg.det(M)

def inverseByAdjointMatrix(A):
  detA = np.linalg.det(A)
  (n,m) = A.shape
  adjA = np.zeros((n,m))

  for i in range(0,n):
    for j in range(0,m):
      adjA[j,i]= cofactor(A,i,j)

  if detA != 0.0:
      return(1./detA) * adjA
  else:
      return 0

A = np.array([[2,5,5],[-1,-1,0],[2,4,3]])

Ainv = inverseByAdjointMatrix(A)
Ainv2 = np.linalg.inv(A)
print("A inverse =",Ainv)
print("")
print("A inverse =",Ainv2)

A inverse = [[ 3. -5. -5.]
 [-3.  4.  5.]
 [ 2. -2. -3.]]

A inverse = [[ 3. -5. -5.]
 [-3.  4.  5.]
 [ 2. -2. -3.]]


#  벡터 크기 (norm) 구하기


In [ ]:
#6-21
import numpy as np

a = np.array([[2],[-1]])
b = np.array([[4],[2],[3]])
c = np.array([[1],[-1],[1]])

NormA = np.linalg.norm(a)
# NormA1= np.linalg.norm(a, 1) #L1 norm계산 = 3.0
# NormA2 = np.linalg.norm(a, 2) #p=2 norm계산 = 2.23606797749979
# NormA3 = np.linalg.norm(a, np.inf) #infinity-norm = 2.0
NormB = np.linalg.norm(b)
NormC = np.linalg.norm(c)

print("NormA=",NormA) #루트가 벗겨진 형태로 출력됨
print("NormB=",NormB)
print("NormC=",NormC)

NormA= 2.23606797749979
NormB= 5.385164807134504
NormC= 1.7320508075688772


In [ ]:
#6-22
import numpy as np

u = np.array([2,-2])
v = np.array([1,3])
print("a=",np.vdot(u,v))

u = np.array([2,-2,3])
v = np.array([-2,1,3])
print("b=",np.vdot(u,v))

u = np.array([1,2,-1,3])
v = np.array([2,-3,1,4])
print("c=",np.vdot(u,v))

u = np.array([2,-2,4])
v = np.array([-1,1,1])
print("d=",np.vdot(u,v))

a= -4
b= 3
c= 7
d= 0
