In [ ]:
import numpy as np

a = np.array([[0.,1.],[-2.,-3.]])
w,v = np.linalg.eig(a)
print("a고유값: ",w)
print("a고유벡터 \n",v)
print("")

a고유값:  [-1. -2.]
a고유벡터 
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]



In [ ]:
b = np.array([[1.,-1.],[2.,4.]])
w1,v1 = np.linalg.eig(b)
print("b고유값: ",w1)
print("b고유벡터 \n",v1)

b고유값:  [2. 3.]
b고유벡터 
 [[-0.70710678  0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [ ]:
c = np.array([[1.,2.,2.],[0.,2.,1.],[-1.,2.,2.]])
w2,v2 = np.linalg.eig(c)
print("c고유값: ",w2)
print("c고유벡터 \n",v2)

c고유값:  [2.00000004 1.99999996 1.        ]
c고유벡터 
 [[ 8.94427191e-01 -8.94427191e-01  5.77350269e-01]
 [ 4.47213595e-01 -4.47213595e-01  5.77350269e-01]
 [ 1.57560595e-08  1.57560598e-08 -5.77350269e-01]]


In [ ]:
d = np.array([[1.,0.,-1.],[1.,2.,1.],[2.,2.,3.]])
w3,v3 = np.linalg.eig(d)
print("d고유값: ",w3)
print("d고유벡터 \n",v3)

d고유값:  [2. 3. 1.]
d고유벡터 
 [[-6.66666667e-01 -4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01  4.08248290e-01 -7.07106781e-01]
 [ 6.66666667e-01  8.16496581e-01  1.75541673e-16]]


In [ ]:
e = np.array([[1.,-3.,3.],[3.,-5.,3.],[6.,-6.,4.]])
w4,v4 = np.linalg.eig(e)
print("e고유값: ",w4)
print("e고유벡터 \n",v4)

e고유값:  [ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]
e고유벡터 
 [[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]


In [ ]:
f = np.array([[1.,-1.,0.],[-1.,2.,-1.],[0.,-1.,1.]])
w5,v5 = np.linalg.eig(f)
print("f고유값: ",w5)
print("f고유벡터 \n",v5)

f고유값:  [ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]
f고유벡터 
 [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  2.61239546e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
